server:
  port: 8090

spring:
  rabbitmq:
    addresses: localhost:5672
    password: admin
    username: admin
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 162
      concurrency: 4
      max-concurrency: 8
      prefetch: 162
  cloud:
    function:
      routing-expression: headers['spicy']
    stream:
      rabbit:
          default:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              max-concurrency: 8
              transacted: true
            producer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
      default:
        contentType: application/json
      bindings:
        foodordersupplier-out-0:
          destination: functionRouter-in-0
        functionRouter-in-0:
          destination: functionRouter-in-0
          group: router
        functionRouter-out-0:
          destination: functionRouter-out-0
          group: ouster
spring.h2.console.enabled: true
spring.h2.console.path: /h2
